apiVersion: v1
kind: PersistentVolume
metadata:
  name: kf2-pv
  namespace: kf2
spec:
  capacity:
    storage: 50Gi # recommended in case you want to add workshop maps later on
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kf2-storage
  local:
    path: /path/to/location # choose a path on your local machine where you want to mount the files of the server
  nodeAffinity:
    required:
     nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - hostname # you can get this value by running `kubectl get nodes`, and copy pasting the name that appears
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kf2-pvc
  namespace: kf2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kf2-storage
  resources:
    requests:
      storage: 50Gi